-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: Nov 07, 2025 at 04:39 AM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.0.30

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `sugandhak`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `a_id` int(10) NOT NULL,
  `a_email` varchar(50) DEFAULT NULL,
  `a_pwd` varchar(30) DEFAULT NULL,
  `a_time` varchar(100) DEFAULT NULL,
  `a_status` int(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`a_id`, `a_email`, `a_pwd`, `a_time`, `a_status`) VALUES
(1, 'meet@gmail.com', '262006', NULL, 1);

-- --------------------------------------------------------

--
-- Table structure for table `category`
--

CREATE TABLE `category` (
  `cat_id` int(11) NOT NULL,
  `cat_nm` varchar(100) DEFAULT NULL,
  `cat_img` longtext DEFAULT NULL,
  `cat_time` varchar(60) NOT NULL,
  `cat_status` int(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `category`
--

INSERT INTO `category` (`cat_id`, `cat_nm`, `cat_img`, `cat_time`, `cat_status`) VALUES
(1, 'For Men', '2025-09-24_product24.png', '2025-09-24', 1),
(2, 'For Women', '2025-09-24_product23.png', '2025-09-24', 1),
(3, 'For Unisex', '2025-09-24_product12.png', '2025-09-24', 1),
(4, 'Gift Sets', '2025-09-24_product7.png', '2025-09-24', 1),
(5, 'Attar', '2025-10-06_attar1.png', '2025-10-06', 1),
(6, 'Body Spray', '2025-10-09_bodyspray1.png', '2025-10-09', 1),
(7, 'Room Spray', '2025-11-06_room_spray1.png', '2025-11-06', 1);

-- --------------------------------------------------------

--
-- Table structure for table `contact`
--

CREATE TABLE `contact` (
  `co_id` int(10) NOT NULL,
  `co_fnm` varchar(255) DEFAULT NULL,
  `co_email` varchar(100) DEFAULT NULL,
  `co_msg` longtext DEFAULT NULL,
  `co_time` varchar(100) DEFAULT NULL,
  `co_status` int(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `hero`
--

CREATE TABLE `hero` (
  `h_id` int(100) NOT NULL,
  `h_nm` varchar(255) DEFAULT NULL,
  `h_img` longtext DEFAULT NULL,
  `h_time` int(60) DEFAULT NULL,
  `h_status` int(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `hero`
--

INSERT INTO `hero` (`h_id`, `h_nm`, `h_img`, `h_time`, `h_status`) VALUES
(1, 'Flawor perfumes', '25-09-04_hero-1df.png', 2025, 1),
(2, 'wood perffume', '25-08-31_hero-2.jpg', 2025, 1);

-- --------------------------------------------------------

--
-- Table structure for table `latest_product`
--

CREATE TABLE `latest_product` (
  `l_id` int(50) NOT NULL,
  `l_nm` varchar(100) DEFAULT NULL,
  `l_description` longtext DEFAULT NULL,
  `l_img` longtext DEFAULT NULL,
  `l_time` varchar(60) DEFAULT NULL,
  `l_status` int(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `latest_product`
--

INSERT INTO `latest_product` (`l_id`, `l_nm`, `l_description`, `l_img`, `l_time`, `l_status`) VALUES
(1, 'Irons Instense', 'This is Irons Instense perfumes', '2025-09-19_new1.png', '2025-09-19', 1),
(2, 'Breaker Instense', 'This is Hulk Breaker instense', '2025-09-19_new2.png', '2025-09-19', 1),
(3, 'shadow Instense', 'This is Shadow instense Perfume', '2025-09-19_new12.png', '2025-09-19', 1),
(4, 'Smoky Instense', 'This is smoky instense perfume', '2025-09-19_new21.png', '2025-09-19', 1),
(5, 'Miolnir Instense', 'This is Thor Instense Perfume', '2025-09-28_thor.png', '2025-09-28', 1);

-- --------------------------------------------------------

--
-- Table structure for table `orders`
--

CREATE TABLE `orders` (
  `o_id` int(4) NOT NULL,
  `o_fnm` varchar(100) DEFAULT NULL,
  `o_lnm` varchar(100) DEFAULT NULL,
  `o_country` varchar(100) DEFAULT NULL,
  `o_address_line1` longtext DEFAULT NULL,
  `o_address_line2` longtext DEFAULT NULL,
  `o_city` varchar(100) DEFAULT NULL,
  `o_state` varchar(100) DEFAULT NULL,
  `o_pincode` varchar(100) DEFAULT NULL,
  `o_phone` varchar(10) DEFAULT NULL,
  `o_email` varchar(100) DEFAULT NULL,
  `o_note` longtext DEFAULT NULL,
  `o_pid` longtext DEFAULT NULL,
  `o_uid` int(4) DEFAULT NULL,
  `o_order_key` varchar(100) DEFAULT NULL,
  `o_payment` varchar(255) DEFAULT NULL,
  `o_time` varchar(100) DEFAULT NULL,
  `o_status` varchar(10) DEFAULT 'pending'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

CREATE TABLE `products` (
  `p_id` int(4) NOT NULL,
  `p_cat` varchar(4) DEFAULT NULL,
  `p_nm` varchar(255) DEFAULT NULL,
  `p_price` bigint(20) DEFAULT NULL,
  `p_img` longtext DEFAULT NULL,
  `p_short_desc` longtext DEFAULT NULL,
  `p_weight` varchar(255) DEFAULT NULL,
  `p_description` longtext DEFAULT NULL,
  `p_add_info` longtext DEFAULT NULL,
  `p_flavor` varchar(100) DEFAULT NULL,
  `p_time` varchar(100) DEFAULT NULL,
  `p_status` int(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`p_id`, `p_cat`, `p_nm`, `p_price`, `p_img`, `p_short_desc`, `p_weight`, `p_description`, `p_add_info`, `p_flavor`, `p_time`, `p_status`) VALUES
(1, '1', 'Shadow Intense', 499, '2025-09-24_product1.png', 'A daring blend of lavender, apple, black pepper, and leather—Shadow Intense is Sugandhak Perfume’s tribute to bold nights and unforgettable impressions.', '100ml', '\"Shadow Intense\" by Sugandhak Perfume is a bold, aromatic fragrance crafted for those who command attention. The promotional image showcases the bottle in a natural setting, surrounded by symbolic ingredients that reflect its layered scent profile. Lavender sprigs, crisp apple, rugged pine cone, and amber-toned resin evoke the top, middle, and base notes, creating a visual narrative of intensity and elegance. The bottle stands as the centerpiece—sleek, confident, and ready to make a statement.', 'Fragrance Family: Aromatic Woody\r\n\r\nTarget Audience: Party-goers, night owls, and bold personalities\r\n\r\nIdeal Season: Autumn/Winter\r\n\r\nLongevity: 8–10 hours\r\n\r\nSillage: Strong and lingering\r\n\r\nDesign Notes: Natural textures contrast with the polished bottle, reinforcing the duality of wildness and refinement\r\n\r\nBrand Message: “Unleash your shadow. Let your intensity speak louder than words.”', 'Spicy', '2025-09-24', 1),
(2, '1', 'Woody Perfume', 699, '2025-09-24_product2.png', 'A bold, woody blend of whiskey, leather, and sandalwood—WOODY is your signature scent for powerful nights and unforgettable impressions.', '100ml', 'WOODY by Sugandhak Perfume is a rich, masculine fragrance that blends smoky, spicy, and earthy tones into one bold experience. The dark brown bottle with a golden cap reflects the depth and luxury of the scent inside. With whiskey and tobacco at the top, leather and oud at the heart, and warm cinnamon and sandalwood at the base, this perfume is made for those who live with intensity and style.', 'Fragrance Type: Woody Spicy\r\n\r\nTop Notes: Whiskey, Black Pepper, Tobacco\r\n\r\nMiddle Notes: Leather, Agerwood (Oud), Coriander, Patchouli\r\n\r\nBase Notes: Cinnamon, Vanilla, Sandalwood\r\n\r\nLongevity: 8–10 hours\r\n\r\nSillage: Strong and noticeable\r\n\r\nBest For: Evening wear, winter season, parties\r\n\r\nAudience: Confident, bold personalities\r\n\r\nDesign Language: Dark elegance with golden luxury\r\n\r\nBrand Message: “Let your scent speak louder than your words.”', 'Stronge', '2025-09-24', 1),
(3, '2', 'Smokey Instense', 349, '2025-09-24_product3.png', 'A warm blend of whiskey, oud, and cinnamon—Smokey Intense is your signature scent for bold evenings and deep vibes.', '50ml', 'Smokey Intense is a bold and exotic fragrance from Sugandhak Perfume, crafted for those who love mystery and depth. The bottle features a striking black-to-orange gradient with a golden cap, symbolizing warmth and intensity. The scent opens with a splash of whiskey, moves into rich oud and patchouli, and settles into a cozy blend of cinnamon and vanilla. It’s smoky, spicy, and unforgettable—perfect for nights that leave a lasting impression.', 'Fragrance Type: Smoky, Rich, Spicy\r\n\r\nTop Note: Whiskey\r\n\r\nMiddle Notes: Oud, Patchouli, Sandalwood\r\n\r\nBase Notes: Cinnamon, Vanilla\r\n\r\nLongevity: Long-lasting (8+ hours)\r\n\r\nSillage: Strong and noticeable\r\n\r\nBest For: Nighttime, winter, cozy settings\r\n\r\nAudience: Confident, mysterious personalities\r\n\r\nDesign Language: Gradient bottle with golden accents for a premium, intense look\r\n\r\nBrand Message: “Let your intensity speak.”', 'Sweet', '2025-09-24', 1),
(4, '3', 'Gallant Instense', 549, '2025-09-24_product4.png', 'Fresh citrus meets smooth rose and grounding sandalwood—Gallant is your signature scent for graceful confidence and everyday charm.', '100ml', 'Gallant is a refined and confident fragrance from Sugandhak Perfume, crafted for those who blend charm with strength. The scent opens with fresh citrus and sea water, flows into a floral-spicy heart of rose and cardamom, and settles into a deep, earthy base of vetiver, sandalwood, and musk. The black bottle with golden accents reflects bold elegance, while the ingredients tell a story of freshness, depth, and timeless masculinity.', 'Fragrance Type: Fruity, Floral, Earthy\r\n\r\nTop Notes: Lemon, Orange, Petitgrain, Sea Water\r\n\r\nMiddle Notes: Rose, Cardamom, Sage, Jasmine, Rosemary\r\n\r\nBase Notes: Oakmoss, Brazilian Rosewood, Vetiver, Sandalwood, Musk\r\n\r\nLongevity: Long-lasting (8+ hours)\r\n\r\nSillage: Moderate to strong\r\n\r\nBest For: Daytime, spring/summer, formal or casual wear\r\n\r\nAudience: Elegant, confident personalities\r\n\r\nDesign Language: Black bottle with gold text—classic, bold, and premium\r\n\r\nTagline: “Walk tall, speak kindly.”', 'spicy', '2025-09-24', 1),
(5, '4', 'Euphoria Quartet', 399, '2025-09-24_product7.png', 'A pocket-sized collection of four vibrant fragrances—Sugandhak Perfume’s 10ml set is your go-to for everyday freshness and seasonal charm.', '40ml', 'This elegant 4-bottle set from Sugandhak Perfume brings together a seasonal mix of fresh, fruity, earthy, and herbal scents. Each 10ml bottle is color-coded and icon-marked for easy identification:\r\n\r\n🍓 Strawberry – Sweet and playful\r\n\r\n🍋 Lemon – Fresh and zesty\r\n\r\n🍁 Maple Leaf – Warm and cozy\r\n\r\n🌿 Green Leaf – Herbal and calming\r\n\r\nCompact and stylish, this set is perfect for travel, gifting, or switching up your scent based on mood or occasion.', 'Type: Fruity, Fresh, Herbal, Earthy\r\n\r\nVolume: 10ml / 0.34 fl oz per bottle\r\n\r\nLongevity: Medium to long-lasting\r\n\r\nBest For: Everyday use, summer, travel\r\n\r\nAudience: Anyone who loves variety and convenience\r\n\r\nDesign Language: Color-coded bottles with playful icons for instant scent recognition\r\n\r\nTagline: “Life in full bloom.”', 'Mix flavors', '2025-09-24', 1),
(6, '1', 'Hero Perfume', 699, '2025-09-24_product5.png', 'Sugandhak Perfume – A bold yet elegant fragrance with the sweetness of plum, floral freshness of geranium, and a deep smoky tobacco base. Perfect for those who love timeless sophistication.', '100ml', 'Discover the essence of elegance with Sugandhak Perfume, crafted to leave a lasting impression.\r\n\r\nThe Top Note of Plum adds a luscious sweetness that instantly captivates.\r\n\r\nThe Middle Note of Geranium brings floral freshness with a refined charm.\r\n\r\nThe Base Note of Tobacco lingers with warmth and depth, making it irresistibly bold and timeless.\r\n\r\nThis fragrance is designed for individuals who value luxury, uniqueness, and long-lasting character in their scent. Ideal for evening wear, special occasions, or whenever you want to stand out.', 'Brand: Sugandhak Perfume\r\n\r\nFragrance Family: Fruity, Floral, Woody\r\n\r\nTop Note: Plum 🍑\r\n\r\nMiddle Note: Geranium 🌺\r\n\r\nBase Note: Tobacco 🌿\r\n\r\nGender: Unisex (For Men & Women)\r\n\r\nOccasion: Evening wear, Special events, Daily elegance\r\n\r\nLongevity: Long-lasting\r\n\r\nIdeal for: Perfume lovers who appreciate bold & elegant scents', 'Alcohol', '2025-09-24', 1),
(7, '3', 'Blazzes', 499, '2025-09-26_product6.png', 'Bold. Fresh. Magnetic. Sugandhak Perfume blends spicy pink pepper with lush florals and warm woods for a scent that turns heads and stays unforgettable.', '100ml', 'Sugandhak Perfume – EAU DE PARFUM A vibrant fusion of spice, florals, and warmth, Sugandhak Perfume is crafted for those who command attention. The top notes burst with pink pepper, lychee, cucumber, and lemongrass—an electrifying opening that’s both fresh and provocative. As it settles, delicate florals like freesia, peony, and osmanthus dance with green tea, creating a heart that’s elegant yet energetic. Finally, the base lingers with white musk, bamboo, ambergris, and cashmere wood—leaving behind a trail of sensual sophistication.', 'Sugandhak Blaze is a 100 ml Eau de Parfum crafted for those who live boldly and leave a lasting impression. Designed as a unisex fragrance, it balances fiery top notes with soft florals and warm woods, making it ideal for evening wear, parties, or any moment that demands attention. The scent lasts 6–8 hours, evolving beautifully on the skin with each passing hour. Housed in a premium glass bottle with golden accents, Sugandhak Blaze belongs to the Floral Woody Musk family and is proudly made in India. Every detail—from the vibrant ingredients to the elegant packaging—reflects a commitment to luxury, energy, and unforgettable style.', 'Spicy', '2025-09-26', 1),
(8, '3', 'Neroli Sun', 399, '2025-09-26_product8.png', 'An exotic and refreshing Eau de Parfum featuring juicy Watermelon, Lemon, and Mint on top, a tropical floral heart of Jasmine, Frangipani, and Neroli, and a serene base of Musk, Cedarwood, and Bamboo. Ideal for a crisp, clean, and unique everyday signature scent.', '100ml', 'Sugandhak Parfum is a bright, watery-fresh fragrance with a lush floral heart and a soft, woody base. It offers an invigorating opening that mellows into an elegant, sun-drenched floral bouquet before settling into a grounding, tranquil finish.\r\n\r\nTop Notes: The scent opens with a burst of cooling refreshment from Watermelon, the zesty tartness of Lemon, and the crisp, clean sensation of Mint. This combination creates an immediate feeling of energy and brightness.\r\n\r\nMiddle Notes: The heart of the fragrance blooms with a sophisticated blend of white and exotic flowers. Jasmine adds a clean, sweet narcotic touch, Frangipani provides a creamy, tropical sweetness, and Neroli introduces a hint of green, citrusy bitterness, giving the perfume a complex, radiant warmth.\r\n\r\nBase Notes: The dry-down is smooth and enduring, built on a comforting foundation of soft Musk, the dry, masculine elegance of Cedarwood, and a light, airy touch of Bamboo, which adds a unique green, earthy depth to the lasting impression.', 'Product Name: SUGANDHAK PARFUM EAU DE PARFUM\r\n\r\nConcentration: Eau de Parfum (EDP)\r\n\r\nVolume: 100 ml / 3.4 fl oz\r\n\r\nScent Family: Fresh, Aquatic, Floral, Woody\r\n\r\nBest Worn: Spring and Summer, daytime use\r\n\r\nFeel: Energizing, soothing, and elegant', 'Woody', '2025-09-26', 1),
(9, '3', 'Petal Drift', 449, '2025-09-26_product10.png', 'A warm, spicy, and woody-oriental fragrance. It opens with Bergamot, Pear, and Cardamom, transitions to an earthy heart of Jasmine, Vetiver, and Nutmeg, and finishes with a luxurious, long-lasting base of Oud, Sandalwood, and Vanilla.', '100ml', 'The notes you provided are for a second perfume from the brand Sugandhak Perfume (from the image file product10.jpg).\r\n\r\nHere is the requested description, short description, and additional information for the Green Bottle Sugandhak Perfume (Notes: Bergamot, Pear, Cardamom, Roseemary, Jasmine, Vetiver, Nutmeg, Neroli, Oud, Patchouli, Vanilla, Sandalwood).\r\n\r\nSUGANDHAK PERFUME (Green Bottle)\r\nDescription\r\nThis fragrance is a sophisticated, warm, and spicy composition with a fresh, bright opening and a deep, luxurious woody-oriental base. It perfectly balances fruity sweetness with aromatic spice and grounding woods.\r\n\r\nTop Notes: The opening is a fresh and vibrant blend of zesty Bergamot and the smooth, subtle sweetness of Pear. This freshness is immediately warmed and spiced up by aromatic Cardamom and herbal Rosemary, creating a complex and invigorating start.\r\n\r\nMiddle Notes: The heart is rich and earthy, featuring the clean floralcy of Jasmine and the smoky, grassy depth of Vetiver. This is enhanced by the warm, pungent spice of Nutmeg and the crisp, green floral hint of Neroli, forming a textured and robust middle layer.\r\n\r\nBase Notes: The fragrance settles into a powerful, opulent, and lasting finish. It is defined by the dark, resinous intensity of Oud and Patchouli, the creamy comfort of Vanilla, and the rich, milky smoothness of Sandalwood. This dry-down is intoxicating, warm, and highly diffusive.', 'Product Name: SUGANDHAK PERFUME (Specific variant name is not provided, so refer to it by notes/bottle)\r\n\r\nConcentration: Eau de Parfum (EDP)\r\n\r\nVolume: 100 ml / 3.4 fl oz\r\n\r\nScent Family: Woody, Spicy, Oriental\r\n\r\nBest Worn: Autumn and Winter; Evening and formal wear.\r\n\r\nFeel: Luxurious, confident, deep, and sensual.\r\n\r\nKey Accord: An elegant contrast between fresh aromatics (Rosemary/Vetiver) and dark woods (Oud/Sandalwood).', 'Sweet', '2025-09-26', 1),
(10, '3', 'Frangipani Chill', 599, '2025-09-26_product9.png', 'Sweet meets spice in Sugandhak Ember—a captivating blend of strawberry, cinnamon, and patchouli for unforgettable elegance.', '90 ml', 'Sugandhak Ember – EAU DE PARFUM Sugandhak Ember ignites the senses with a bold blend of sweetness and spice. The top notes of strawberry, orange, and mint offer a refreshing burst that’s playful yet refined. As the fragrance unfolds, chamomile, honey, and cinnamon create a warm, comforting heart—like golden light on velvet skin. The base settles into a rich trail of cinnamon, star anise, and patchouli, leaving behind a signature that’s both mysterious and magnetic. Crafted for those who move with quiet confidence and bold intent.', 'Sugandhak Ember is a 100 ml Eau de Parfum designed for those who embrace warmth and allure. This unisex fragrance opens with fruity freshness, softens into herbal sweetness, and finishes with spicy depth—making it perfect for intimate evenings or upscale gatherings. With a wear time of 6–8 hours, it evolves beautifully throughout the day. The perfume is housed in a matte teal glass bottle with a golden cap, reflecting its luxurious and modern spirit. Belonging to the Spicy Woody Amber family, Sugandhak Ember is proudly made in India and crafted to leave a lasting impression.', 'Alcohol', '2025-09-26', 1),
(11, '2', 'Amber Whisper	', 399, '2025-09-26_product11.png', 'A refreshing and uplifting EDP with notes of Watermelon, Lemon, and Mint, layered over sunny Jasmine and Frangipani, finishing with a clean blend of Cedarwood, Musk, and Bamboo.\r\n\r\n', '100ml', 'This is a vibrant and cooling fragrance, perfect for summer. It captures the essence of a fresh fruit cocktail blended with soft white florals, grounded by subtle woods.\r\n\r\nTop Notes: The scent bursts with the juicy sweetness of Watermelon, the sharp, citrusy tang of Lemon, and the refreshing coolness of Mint. This provides an immediate, invigorating splash of freshness.\r\n\r\nMiddle Notes: The heart introduces a bright, sunny floral blend: the rich, sweet aroma of Jasmine, the creamy, tropical sweetness of Frangipani, and the bitter-green, clean scent of Neroli.\r\n\r\nBase Notes: The dry-down is light, woody, and clean, featuring soft, comforting Musk, the dry elegance of Cedarwood, and a unique, moist, green touch of Bamboo.', 'Scent Family: Fresh, Aquatic, Floral, Woody.\r\n\r\nBest Worn: Day Time, Summer.\r\n\r\nVibe: Energizing, playful, clean, and breezy.', 'Stronge', '2025-09-26', 1),
(12, '1', 'Aqua Brav', 499, '2025-09-26_product13.png', 'A bright and refreshing aromatic fragrance opening with a blast of Bergamot, Lemon, and Mint. Its heart is a clean blend of Jasmine and Neroli, and it dries down to a light, enduring base of Musk, Cedarwood, and Bamboo.\r\n\r\n', '50ml', 'Aqua BRAV is a sophisticated and bold fragrance that centers on a timeless duality between luminous freshness and deep, comforting sweetness. It opens with the clear, invigorating zest of Bergamot, which provides an instant burst of clean, slightly spicy citrus energy. The heart is mysterious and complex, likely containing warm spices or dark woods (though not explicitly listed in the visual notes). The entire composition is grounded by a smooth, creamy, and lasting base of pure Vanilla, creating a sensual, warm, and highly wearable finish that lingers beautifully.', 'Scent Family: Aromatic, Citrus, Fresh, Aquatic.\r\n\r\nBest Worn: Day Time, Spring and Summer.\r\n\r\nVibe: Energizing, clean, uplifting, and sporty.\r\n\r\nKey Accord: A highly refreshing mix of citrus (Bergamot, Lemon) and aromatic greenery (Mint, Bamboo).', 'Stronge', '2025-09-26', 1),
(13, '2', 'Black Orchid', 499, '2025-09-28_product12.png', 'SUGANDHAK PARFUM EDP (56ml) is a rich, fruity-woody gourmand fragrance. It opens with Raspberry and Fig, evolves into a daring heart of Truffle, Black Currant, and Incense, and finishes with a deeply warm blend of Vanilla, Vetiver, and Amber Woods. A sophisticated and long-lasting scent with a compelling contrast of sweet and earthy notes.', '100ml', 'A captivating and sophisticated fragrance that balances lush fruit, gourmand warmth, and rich woods. This complex scent opens with a delicious embrace of Raspberry and Fig, subtly smoothed by Vanilla Bean and Mallow. The heart reveals a daring and intriguing blend of notes, where the tart burst of Black Currant meets the aromatic lift of Basil, the dark earthiness of Truffle, and the mysterious depth of Incense. It finally settles into a luxurious and enduring base of creamy Vanilla, smoky Vetiver, and warm Amber Woods, leaving a memorable and alluring trail. Perfect for those who seek a unique, long-lasting scent that is both sweet and powerfully grounded.', 'Brand Name: SUGANDHAK PARFUM\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume: 56 ml / 1.7 fl. oz.\r\n\r\nScent Profile: A rich, complex blend featuring prominent fruity, gourmand, woody, and aromatic elements.', 'Sweet', '2025-09-28', 1),
(14, '2', 'BLUSH OUD RADIANCE', 399, '2025-09-28_product14.png', 'BLUSH OUD RADIANCE EDP (SUGANDHAK PERFUME): A radiant floral gourmand scent featuring delicate Rose Milk, sweet Almond and Meringue heart notes, and a warm, creamy base of Vanilla and Sandalwood. Elegant, soft, and long-lasting for a captivating everyday finish.', '50ml', 'BLUSH OUD RADIANCE by SUGANDHAK PERFUME - The Epitome of Sweet Elegance\r\n\r\nStep into a dreamy world with Blush Oud Radiance, a captivating Eau de Parfum that blends romantic sweetness with sophisticated warmth. This fragrance is an ode to delicate femininity, presenting a gourmand journey that is both comforting and alluring.\r\n\r\nThe scent opens with a soft, ethereal embrace of Rose Milk and sparkling Pink Sugar, creating an instantly romantic and tender first impression. The heart blossoms into a creamy indulgence of Sweet Almond and airy Meringue, adding a delicious, velvety texture that balances the initial floral lightness.\r\n\r\nAs the fragrance settles, it deepens into an irresistible, long-lasting base of smooth Creamy Sandalwood and rich Vanilla Pods. A subtle, soft Oud Accord is woven in with White Musk, providing an elegant, sophisticated anchor that leaves a radiant, memorable trail. Blush Oud Radiance is perfect for those who seek a delicate yet powerful signature scent.', 'Scent Profile:Creamy, Sweet, Powdery, and Elegant with a hint of warmth.\r\nIdeal For:Women (Unisex for those who love sweet/gourmand scents).\r\nOccasion:Perfect for daily wear, office, daytime events, and cozy evenings.\r\nLongevity:Excellent (Known to be a high-performing EDP, typically 6+ hours).\r\nSillage (Projection)	Moderate to Strong—it creates a beautiful, noticeable scent bubble.\r\nInspiration/Vibe:Often compared to the creamy-sweet, modern feminine luxury fragrances.\r\nUsage Tip:For best performance, apply to pulse points (neck, wrists, behind ears) and allow to dry without rubbing.', 'Sweet', '2025-09-28', 1),
(15, '2', 'Cherry Blossom Scent', 349, '2025-09-28_product15.png', 'SUGANDHAK CHERRY BLOSSOM EDP (50ml): A delicate and creamy floral perfume. It features soft Roses and Almond leading to a heart of Cherry Blossom and Jasmine, drying down to a comforting base of Vanilla, Sandalwood, and Coconut. Sweet, gentle, and utterly feminine.', '50ml', 'SUGANDHAK PERFUME - Cherry Blossom Scent\r\n\r\nEmbrace the delicate beauty of a spring garden with this exquisite floral EDP. This fragrance opens with a soft, romantic blend of fresh Roses and creamy Magnolia, beautifully balanced by a subtle, sweet accent of Almond.\r\n\r\nThe heart of the scent blooms with the elegant aroma of Cherry Blossom and luxurious Jasmine, given a subtle, sophisticated warmth by a hint of Clove. This elegant floral core gives way to a dreamy, comforting base where the earthiness of Patchouli and the warmth of Sandalwood are smoothed by creamy Coconut and rich Vanilla.\r\n\r\nThis perfume is a tender, sophisticated, and memorable scent—perfect for brightening your mood and leaving a gentle, alluring trail.', 'Scent Profile:Soft Floral, Powdery, Creamy, and Sweet (due to coconut/vanilla base).\r\nIdeal For:Women\r\nIdeal Season:Spring and Summer; versatile for daytime wear.\r\nCharacter:Gentle, Romantic, Fresh, and Clean.\r\nLongevity:Moderate to Long-Lasting (EDP concentration).\r\nVersatility:Excellent for daily wear, office environment, and casual outings.', 'Sweet', '2025-09-28', 1),
(16, '4', 'Blossom Scent Combo', 349, '2025-09-28_product16.png', 'SUGANDHAK CHERRY BLOSSOM EDP (50ml): A delicate and creamy floral perfume. It features soft Roses and Almond leading to a heart of Cherry Blossom and Jasmine, drying down to a comforting base of Vanilla, Sandalwood, and Coconut. Sweet, gentle, and utterly feminine.', '40ml', 'SUGANDHAK PERFUME - Cherry Blossom Scent\r\n\r\nEmbrace the delicate beauty of a spring garden with this exquisite floral EDP. This fragrance opens with a soft, romantic blend of fresh Roses and creamy Magnolia, beautifully balanced by a subtle, sweet accent of Almond.\r\n\r\nThe heart of the scent blooms with the elegant aroma of Cherry Blossom and luxurious Jasmine, given a subtle, sophisticated warmth by a hint of Clove. This elegant floral core gives way to a dreamy, comforting base where the earthiness of Patchouli and the warmth of Sandalwood are smoothed by creamy Coconut and rich Vanilla.\r\n\r\nThis perfume is a tender, sophisticated, and memorable scent—perfect for brightening your mood and leaving a gentle, alluring trail.', 'Scent Profile:Soft Floral, Powdery, Creamy, and Sweet (due to coconut/vanilla base).\r\nIdeal For:Women\r\nIdeal Season:Spring and Summer; versatile for daytime wear.\r\nCharacter:Gentle, Romantic, Fresh, and Clean.\r\nLongevity:Moderate to Long-Lasting (EDP concentration).\r\nVersatility:Excellent for daily wear, office environment, and casual outings.', 'Mix flavors', '2025-09-28', 1),
(17, '1', 'Dark Side', 499, '2025-09-28_product17.png', 'SUGANDHAK dark side EDP (100ml): A bold, intense, and mysterious fragrance for evening wear. Features powerful notes of Black Pepper, Leather Accord, and deep Amber woods. Long-lasting, confident, and highly addictive.', '100ml', 'SUGANDHAK PERFUME - dark side: The Scent of Intensity and Mystery\r\n\r\nEmbrace the night with dark side, a powerful and enigmatic Eau de Parfum designed for those who command attention. Housed in a striking, deep-blue glass bottle, this fragrance is a statement of confidence and masculine sophistication.\r\n\r\nThe scent opens with a sharp, invigorating burst of Black Pepper and fresh Bergamot, immediately establishing a dynamic presence. This energy mellows into a rich, complex heart of raw Leather and smoky Incense, spiced with warm Cinnamon and deep woods.\r\n\r\nThe true intensity lies in the base, where creamy Amber, earthy Patchouli, and Vetiver blend with a powerful Musk accord. This blend ensures exceptional longevity and sillage, leaving an unforgettable, captivating trail that is perfect for special evenings and cool nights.', 'Scent Profile:Intense, Warm, Spicy, Leathery, and Deeply Woody.\r\nIdeal For:Men (or anyone seeking a bold, dark, and powerful scent).\r\nIdeal Season:Autumn and Winter.\r\nIdeal Time of Day:Evening and Night Events.\r\nLongevity:Excellent (High-Concentration EDP for maximum lasting power).\r\nThe Vibe:Confidence, Authority, Sophistication, Night-Out Essential.', 'Spicy', '2025-09-28', 1),
(18, '3', 'POISON INTENSE', 499, '2025-09-28_product19.png', 'SUGANDHAK POISON INTENSE (Extrait de Parfum): The highest concentration of allure. A powerful, spicy-aromatic blend of fresh Basil, warm Cinnamon, and a long-lasting Musk base. For maximum projection and intense longevity.\r\n\r\n', '50ml', 'SUGANDHAK - POISON INTENSE: The Ultimate Expression of Allure\r\n\r\nDare to wear the poison. POISON INTENSE is an Extrait de Parfum—the highest concentration of fragrance oil—designed for unparalleled projection and lasting power. Housed in a captivating deep purple bottle, this scent is a bold, sensual masterpiece that leaves a magnetic impression.\r\n\r\nThe fragrance immediately delivers a surprising and sharp aromatic lift with fresh Basil. This invigorating green note quickly blends into the warm, spicy heart of Cinnamon, which provides depth and an inviting warmth.\r\n\r\nThe simplicity of the composition belies its power, settling into a profound, clean base of pure Musk. This powerful base note is what sustains the scent for hours, ensuring a sensual, unforgettable trail that is both provocative and addictive. POISON INTENSE is your signature for making a dramatic entrance.\r\n\r\n', 'Scent Profile:Aromatic, Spicy, Warm, and Intense Musk.\r\nConcentration:Extrait de Parfum (Highest available concentration)\r\nIdeal For:Unisex (Strong projection suitable for bold individuals).\r\nIdeal Season:Autumn, Winter, and Cool Evenings.\r\nLongevity:Exceptional (Extrait concentration ensures 10+ hours).\r\nUsage:Use sparingly; 1-2 sprays are sufficient due to high intensity.', 'Spicy', '2025-09-28', 1),
(19, '3', 'SECRET ESSENCE', 249, '2025-09-28_product20.png', 'SUGANDHAK SECRET ESSENCE (Extrait de Parfum): An invigorating blend of fresh Mint, Apple, and Bergamot. The heart features warm Cardamom and sophisticated Tea Leaves. High concentration for superior longevity and freshness.\r\n\r\n', '50ml', 'SUGANDHAK - SECRET ESSENCE: The Intrigue of Fresh Spices\r\n\r\nUnveil your hidden depth with SECRET ESSENCE, an invigorating Extrait de Parfum that offers maximum concentration for superior longevity and projection. This scent masterfully blends fresh vibrancy with warm, inviting spices.\r\n\r\nThe fragrance opens with an immediate and refreshing burst of energy: zesty Bergamot, cool Mint, and crisp Apple. This bright start leads seamlessly into the complex heart, where delicate Jasmine is warmed by aromatic Cardamom and the subtle bitterness of Tea Leaves. The presence of cardamom and tea creates a sophisticated, intriguing core.\r\n\r\nAs an Extrait de Parfum, it ensures a powerful and elegant trail that lasts all day, perfect for individuals who want a signature scent that is both fresh and deeply aromatic. SECRET ESSENCE is your best-kept secret for daily charm and lasting freshness.', 'Scent Profile:Fresh, Aromatic, Spicy, and Green Tea-like.\r\nConcentration:Extrait de Parfum (Highest concentration for intensity)\r\nIdeal For:Unisex. Excellent daily driver for work or leisure.\r\nIdeal Season:Spring and Summer; also effective year-round.\r\nLongevity:Exceptional (The Extrait formula is designed for all-day wear).\r\nThe Vibe:Clean, Professional, Energizing, and Intriguing.\r\nBottle Design:Round glass bottle with a rich amber-brown liquid and gold cap.', 'Spicy', '2025-09-28', 1),
(20, '1', 'MYSTIC HARMONY', 349, '2025-09-28_product21.png', 'SUGANDHAK MYSTIC HARMONY (Extrait de Parfum): A balanced blend of fresh and mystical notes. Starts with Lemon and Basil, moves to Cardamom and Tea Leaves, and settles on a calming base of Myrrh and Patchouli. High intensity for superior, all-day wear.\r\n\r\n', '50ml', 'SUGANDHAK - MYSTIC HARMONY: A Balanced Journey to Serenity\r\n\r\nDiscover your perfect balance with MYSTIC HARMONY, an Extrait de Parfum that combines vibrant freshness with deep, calming spiritual notes. This intense concentration ensures a long-lasting and powerful aromatic experience.\r\n\r\nThe scent opens with a burst of crisp freshness, featuring zesty Lemon and aromatic Basil, accented by a subtle sweetness of Berries. This bright start gracefully transitions into the exotic and comforting heart, where creamy Ylang-Ylang blends with warm Cardamom and the earthy richness of Tea Leaves.\r\n\r\nThe base is where true harmony is found, with grounding notes of damp Patchouli, ancient Myrrh, and a clean, soft layer of Musk. MYSTIC HARMONY is a sophisticated, versatile fragrance that brings a touch of calm luxury to every day.', 'Scent Profile:Aromatic, Green, Herbal, Fresh Citrus, and Resinous/Earthy.\r\nConcentration:Extrait de Parfum (Highest concentration)\r\nIdeal For:Men. Perfect for professionals or those seeking a calming, distinctive daytime scent.\r\nIdeal Season:Spring and Summer, but the Myrrh and Patchouli make it suitable for year-round use.\r\nLongevity:Exceptional (Extrait formula for maximum performance).\r\nThe Vibe:Calm, Confident, Balanced, Ethereal.', 'Herbal', '2025-09-28', 1),
(21, '3', 'BLUSH MARINE RADIANCE', 399, '2025-09-28_product22.png', 'SUGANDHAK BLUSH MARINE RADIANCE EDP: A crisp, refreshing aquatic fragrance. Features notes of Sea Salt, Lime, and Marine Accord, settling into a clean Musk base. Ideal for daily freshness.\r\n\r\n', '50ml', 'SUGANDHAK - BLUSH MARINE RADIANCE: The Essence of the Open Sea\r\n\r\nCapture the crisp, exhilarating freshness of the ocean with BLUSH MARINE RADIANCE. This vibrant Eau de Parfum is an ode to freedom, clarity, and the boundless energy of the waves.\r\n\r\nThe scent opens with an immediate surge of Marine Accord and sparkling Lime, reminiscent of the morning sea breeze across the water. This bracing freshness is softened in the heart by calming Lavender and delicate Blue Petals, adding a touch of floral elegance to the core.\r\n\r\nAs it settles, a clean, enduring base of White Musk and subtle Cedarwood anchors the fragrance, providing a smooth, masculine finish. BLUSH MARINE RADIANCE is the perfect signature scent for active days and fresh starts.', 'Scent Profile:Aromatic, Green, Herbal, Fresh Citrus, and Resinous/Earthy.\r\nConcentration:Extrait de Parfum (Highest concentration)\r\nIdeal For:Unisex. Perfect for professionals or those seeking a calming, distinctive daytime scent.\r\nIdeal Season:Spring and Summer, but the Myrrh and Patchouli make it suitable for year-round use.\r\nLongevity:Exceptional (Extrait formula for maximum performance).\r\nThe Vibe:Calm, Confident, Balanced, Ethereal.', 'Herbal', '2025-09-28', 1),
(22, '3', 'BLUSH MANGO SPICY', 399, '2025-09-28_product23.png', 'SUGANDHAK BLUSH MANGO SPICY VANILLA EDP: A captivating gourmand blend. Features juicy Mango and a surprising hint of Chili Spice, wrapped in a creamy, sensual base of rich Vanilla.', '50ml', 'SUGANDHAK - BLUSH MANGO SPICY VANILLA: A Tropical Heatwave\r\n\r\nExperience a vibrant and intoxicating journey with BLUSH MANGO SPICY VANILLA. This unique Eau de Parfum captures the lush sweetness of the tropics, elevated by a surprising, fiery spice.\r\n\r\nThe scent opens with the juicy, mouth-watering aroma of Ripe Mango, immediately followed by a thrilling kick of Chili Pepper that adds an unexpected edge. The heart is smooth and comforting, where delicate Vanilla Orchid and calming Lavender soften the initial spice.\r\n\r\nFinally, the fragrance settles into an opulent, warm base of deep Vanilla Absolute and golden Amber. BLUSH MANGO SPICY VANILLA is bold, playful, and addictive—perfect for making a memorable, unforgettable statement.', 'Scent Profile:Fruity Gourmand, Warm Spicy, Tropical, and Sweet (due to vanilla base).\r\nIdeal For:Unisex; perfect for those who enjoy playful, unique, and bold gourmand scents.\r\nIdeal Season:Spring and Summer; the spicy vanilla base also makes it excellent for year-round evening wear.\r\nIdeal Time:Daytime (Playful/Casual) or Evening (Bold/Statement).\r\nThe Vibe:Exotic, Playful, Bold, Sweet with a Spicy Kick.\r\nLongevity:Good (as an Eau de Parfum).\r\nUnique Selling Point:The surprising contrast between sweet tropical Mango and fiery Chili Pepper.\r\nBottle Design:Clear square bottle with a striking orange liquid and cap.', 'Spicy', '2025-09-28', 1),
(23, '1', 'PRIDE INSTENSE', 499, '2025-09-28_product24.png', 'SUGANDHAK PRIDE EDP: A bold, captivating scent featuring the juicy sweetness of Peach, the floral richness of Rose, and the dark, smoky warmth of Tobacco. A sophisticated, statement-making fragrance.\r\n\r\n', '100 ml', 'SUGANDHAK - PRIDE: Bold, Elegant, and Unforgettable\r\n\r\nEmbody confidence and sophistication with PRIDE, a compelling Eau de Parfum that strikes a powerful balance between sweet, floral, and dark notes.\r\n\r\nThe fragrance opens with the lush, ripe sweetness of Peach, providing an inviting and vibrant start. This juicy burst is gracefully joined by a rich, dominant heart of timeless Rose, blending femininity and strength. The ultimate expression of luxury is found in the base, where warm, smoky Tobacco grounds the composition, creating a sensual, long-lasting, and addictive trail. PRIDE is the perfect choice for evening wear and special occasions where a statement is required.', 'Scent Profile:Fruity, Floral, Sweet, and Smoky Tobacco.\r\nIdeal For:Men perfect for those who prefer luxurious, bold, and slightly darker floral scents.\r\nIdeal Season:Autumn and Winter; the warmth of the Tobacco makes it excellent for cooler months.\r\nIdeal Time:Evening, Dates, and Special Occasions (Statement Scent).\r\nThe Vibe:Bold, Elegant, Confident, Luxurious.\r\nLongevity:Very Good (as an Eau de Parfum).\r\nUnique Selling Point:The sophisticated contrast between the soft sweetness of Peach and the rich earthiness of Tobacco.\r\nBottle Design:Square, dark red/amber bottle with a gold cap.', 'Smoky', '2025-09-28', 1),
(24, '2', 'RAVAGE', 399, '2025-09-28_product25.png', 'SUGANDHAK RAVAGE EDP: A powerful, spicy-floral fragrance. Opens with bright Blood Orange, moves to a heart of rich Rose, and dries down to a warm, prominent Cinnamon base. Bold, passionate, and long-lasting.\r\n\r\n', '100 ml', 'SUGANDHAK - RAVAGE: A Fiery and Compelling Aura\r\n\r\nUnleash your captivating presence with RAVAGE, an Eau de Parfum that is as bold and dramatic as its deep red bottle. This fragrance is a powerful statement of passion and confidence.\r\n\r\nThe scent opens with a vibrant, juicy burst of Blood Orange, delivering a sharp, intoxicating freshness. This citrus energy flows into a sophisticated heart dominated by the rich, velvety texture of Rose.\r\n\r\nThe foundation of RAVAGE is built on the warm, inviting spice of Cinnamon. This grounding base ensures excellent longevity and leaves a persistent, sensual, and unforgettable trail. RAVAGE is perfect for evening wear when you want your scent to reflect your irresistible intensity.', 'Scent Profile:Spicy, Zesty Citrus, Rich Floral, and Warm.\r\nIdeal For:Women excellent for individuals seeking a powerful, non-traditional rose scent.\r\nIdeal Season:Autumn and Winter; the warmth and spice are perfect for cooler weather.\r\nIdeal Time:Evening or formal occasions (Statement Scent).\r\nThe Vibe:Passionate, Confident, Intense, and Luxurious.\r\nLongevity:Very Good (as an Eau de Parfum).', 'Spicy', '2025-09-28', 1),
(25, '1', 'Whisky Smoke', 499, '2025-09-29_product18.png', 'The scent is a bold, addictive, and indulgent concoction, opening with a heady mix of Whisky and Tobacco. It mellows into a spicy, warm heart of Cinnamon and Vanilla, and settles on a deep, dark, and long-lasting base of exotic Oudh, warm Sandalwood, Leather, and earthy Patchouli, embodying an aura of sophistication and mystery.\r\n\r\n', '50ml', 'The product in the image is Sugandhak Whisky Smoke Eau De Parfum.\r\n\r\nSince \"Sugandhak\" is a less commonly known brand, and the name \"Whisky Smoke\" is strongly associated with a popular fragrance from the brand \"Beardo,\" the following information is based on the widely known Beardo Whisky Smoke EDP, as is often the case with similar product names in the fragrance market.\r\n\r\nHere is a likely description, fragrance notes, and additional information:', 'Concentration: Eau De Parfum (EDP), indicating a higher concentration of fragrance oils for a longer-lasting scent compared to Eau De Toilette (EDT).\r\n\r\nIdeal Use: Best suited for evening wear, date nights, and cooler weather due to its intense and warm profile.\r\n\r\nVolume: 50ml (as indicated on the bottle).\r\n\r\nAura: Masculine, seductive, bold, sophisticated, and dark.', 'Alcohol', '2025-09-29', 1),
(26, '1', 'ONIX', 449, '2025-09-29_product26.png', 'A fresh, clean, and calming Aromatic EDP with bright Mandarin, soothing Lavender, and grounding Patchouli. Perfect for everyday wear, offering a subtle yet confident scent.\r\n\r\n', '50ml', 'Sugandhak ONIX EDP is a balanced and captivating fragrance that offers a moment of tranquility and confidence. The scent opens with the bright, effervescent burst of Mandarin, providing an immediate sense of refreshment and energy.\r\n\r\nAt its core lies the soothing, aromatic heart of Lavender, a note celebrated for its clean, relaxing, and universally appealing quality. The composition is firmly grounded by the deep, earthy, and woody richness of Patchouli in the base, which ensures longevity and adds a touch of sophistication.\r\n\r\nONIX is a versatile and unisex scent, making it an excellent choice for daily wear, the office, or casual outings where you desire a fragrance that is both comforting and effortlessly chic.', 'Concentration:Eau De Parfum (EDP). Provides better longevity than a standard Eau De Toilette.\r\nLongevity:Moderate to Good (4-6 Hours). Its balanced composition is long-lasting enough for a full workday.\r\nSillage/Projection:Moderate. It offers a pleasant scent trail that is present but non-offensive, perfect for close-quarters environments.\r\nBest For Day Wear (Office, Casual Meetings), Warmer Weather (Spring, Summer). The fresh, aromatic notes are revitalizing in heat.\r\nTarget Audience:Men. The clean freshness of Mandarin and Lavender makes it a scent enjoyed equally by both men and women.\r\nMood/Vibe	Clean, Relaxed, Refreshing, Professional, and Balanced.\r\nApplication Tip:A great fragrance to layer or to wear straight out of the shower for a clean, fresh feeling.', 'Herbal', '2025-09-29', 1),
(27, '1', 'HERO Instense', 499, '2025-09-29_product27.png', 'A bold, modern fragrance that is both fruity-sweet and warmly spicy. The unique opening of Fig leads to a luminous Orange Blossom heart and a sensual Cinnamon base, perfect for the man who wants a scent that is both uplifting and deeply charismatic.\r\n\r\n', '100ml', 'Sugandhak HERO Eau De Parfum is crafted for the confident and effortlessly stylish individual. This dynamic fragrance opens with the intriguing and rarely used note of Fig, offering a fresh, green, and slightly milky sweetness that is immediately captivating.\r\n\r\nThe heart of the scent blossoms with bright and luminous Orange Blossom, injecting a floral freshness that keeps the fragrance energetic and appealing. As the scent settles, it reveals a warm, enveloping base of Cinnamon, providing a spicy, comforting warmth that lingers on the skin. This contrast of fresh fig and warm spice creates a signature scent that is versatile yet sophisticated.', 'Concentration :Eau De Parfum (EDP). Higher concentration for better projection and longevity.\r\nLongevity:Good (5-7 Hours). The spicy and sweet base notes contribute to a respectable lasting power throughout the day.\r\nSillage/Projection:Moderate to Strong. Creates a noticeable, magnetic scent bubble without being overwhelming.\r\nBest For:Day or Night Wear. Its balance of freshness and spice makes it versatile for the office and for evening events.\r\nIdeal Season:All Seasons, but performs exceptionally well in Spring and Autumn.\r\nTarget Audience:Men (Masculine). Suitable for the modern gentleman who is both fresh and warm.\r\nMood/Vibe	Confident, Charismatic, Energetic, and Appealing.', 'Stronge', '2025-09-29', 1),
(28, '1', 'IRONS INTENSE', 699, '2025-10-05_product28.png', 'The Ultimate Breaker: A raw, intense, and electrifying green-woody scent. Experience an unapologetic surge of bright kiwi and deep moss that defines modern intensity.', '100 ml', 'Sugandhak IRONS Intense is a luxurious Eau de Parfum crafted for those who exude power and confidence. The scent opens with a sparkling citrus top note, giving way to the heart of alley rose—a symbol of fiery elegance. Finally, it settles into a rich, mysterious base of plasma oud, creating a long-lasting impression of warmth and intensity.\r\n\r\nPerfect for night events, parties, or moments when you want your presence to be unforgettable.', 'Type: Extrait de Parfum (Long-lasting)\r\n\r\nGender: Unisex (leaning toward masculine)\r\n\r\nLongevity: 10–12 hours\r\n\r\nSillage: Strong, captivating trail\r\n\r\nBest For: Evening wear, special occasions\r\n\r\nBottle Design: Elegant red and gold premium glass bottle', 'Woody', '2025-10-05', 1),
(29, '1', 'Breaker Intense', 599, '2025-10-05_product29.png', 'Breaker Intense by Sugandhak Perfume: A bold green bottle packed with kiwi zest, kale depth, and moss wood fire. Designed for the daring, this EXTRAGI DE PARFUM turns heads and owns the night.', '100 ml', 'Breaker Intense by Sugandhak Perfume is a fearless fusion of exotic botanicals and electrifying energy. Encased in a striking green bottle with a regal gold cap, this EXTRAGI DE PARFUM unleashes a sensory storm that commands attention.\r\n\r\nTop Note – Midrange Kiwi: A vibrant, juicy burst that sparks curiosity.\r\n\r\nMiddle Note – Outland Kale: Earthy and unconventional, adding depth and intrigue.\r\n\r\nBase Notes – Arc-Zest & Rage Moss wood: A dual foundation of zesty brightness and mossy intensity, grounding the fragrance in raw power.\r\n\r\nCrafted for those who break norms and own the night, Breaker Intense is not just a scent—it’s a statement.', 'Breaker Intense by Sugandhak Perfume is a bold EAU DE PARFUM crafted for those who thrive on intensity and individuality. Housed in a striking emerald, green bottle with a luxurious gold cap, this fragrance blends vibrant top notes of Midrange Kiwi with the earthy depth of Outland Kale at its heart. The base is anchored by a powerful duo—Arc-Zest and Rage Moss wood—delivering a zesty brightness and mossy richness that lingers with magnetic allure. Designed for party-ready moments and statement-making nights, Breaker Intense embodies the fearless spirit of the Sugandhak brand.', 'Spicy', '2025-10-05', 1),
(30, '3', 'Strawberry Bloom', 249, '2025-10-05_product30.png', 'A refreshing blend of citrus and berries, wrapped in floral elegance and a warm woody base — Strawberry Bloom is your perfect everyday fragrance.', '50ml', 'Sugandhak Strawberry Bloom captures the playful essence of summer in a bottle. The fragrance opens with a burst of bergamot, strawberry, orange, and lemon, giving a juicy and energizing freshness. The heart unfolds into delicate jasmine and rose petals, balanced with a hint of pine for a clean and natural vibe. Finally, it settles into comforting cedarwood and honey, leaving behind a soft, warm sweetness that lingers beautifully throughout the day.\r\n\r\nPerfect for daytime wear, casual outings, or when you simply want to smell fresh, fruity, and effortlessly charming.', 'Type: Eau de Parfum\r\n\r\nVolume: 50 ml / 1.7 fl.oz.\r\n\r\nGender: Unisex (with a fresh fruity touch)\r\n\r\nLongevity: 6–8 hours\r\n\r\nSillage: Moderate and pleasant\r\n\r\nMood: Fresh • Sweet • Uplifting\r\n\r\nBest For: Daily wear, spring & summer seasons', 'sweet', '2025-10-05', 1),
(31, '1', 'MJOLNIR Intense', 699, '2025-10-05_product31.png', 'Unleash the power of thunder with MJOLNIR Intense, a bold fragrance forged from the storm — fresh, electric, and deeply masculine.', '100 ml', 'Inspired by the mythical hammer of the gods, Sugandhak MJOLNIR Intense embodies raw strength and unstoppable energy. The fragrance opens with a burst of Lightning Citrus, sparking fresh and invigorating sensations. The heart reveals Storm Sage, bringing a crisp herbal intensity that commands attention. Finally, it settles into the deep resonance of Thunder Oak, leaving a powerful, woody trail that endures like a storm’s echo.\r\n\r\nPerfect for nights of power, adventure, and confidence — when you want to leave an unforgettable impression.', 'Type: Eau de Parfum / Long-lasting\r\n\r\nGender: Men\r\n\r\nLongevity: 10–12 hours\r\n\r\nSillage: Strong and bold\r\n\r\nMood: Energetic • Powerful • Electric\r\n\r\nBest For: Evening wear, events, parties\r\n\r\nBottle Design: Deep ocean blue with golden accents – symbolizing lightning and might', 'Stronge', '2025-10-05', 1),
(32, '1', 'Desire Intense', 399, '2025-10-05_product32.png', 'Desire Intense is a bold and sensual fragrance with fresh orange, warm cinnamon, and creamy vanilla musk. Perfect for unforgettable nights.', '50ml', 'Desire Intense by Sugandhak Perfume is crafted for those who love to stand out. It opens with juicy orange and soft vanilla flower, followed by spicy cinnamon at the heart. The base settles into rich vanilla and smooth musk, creating a long-lasting, seductive scent. The bottle features a golden cap and clear glass, reflecting luxury and confidence.', 'Fragrance Family: Oriental Gourmand\r\n\r\nLongevity: 8–10 hours\r\n\r\nSillage: Strong\r\n\r\nBest for: Parties, date nights, bold personalities\r\n\r\nDesign Style: Premium, vibrant, golden-themed', 'Stronge', '2025-10-05', 1),
(33, '2', 'Dream instence', 250, '2025-10-05_product33.png', 'Dream is a soft and elegant fragrance with fresh bergamot, floral jasmine, and warm vanilla. Perfect for calm evenings and graceful charm.', '50ml', 'Dream by Sugandhak Perfume is a tribute to calm confidence and timeless charm. The fragrance opens with the crisp brightness of bergamot, awakening the senses with a fresh citrus spark. At its heart lies jasmine—delicate, floral, and deeply romantic. The base note of vanilla adds warmth and comfort, wrapping the wearer in a gentle, lasting embrace.\r\n\r\nThe bottle design reflects nature and purity, with a copper-toned cap and earthy green background. It’s a perfume that feels like a quiet walk through a blooming garden—peaceful, elegant, and unforgettable.', 'Fragrance Family: Floral Oriental\r\n\r\nLongevity: 6–8 hours\r\n\r\nSillage: Moderate (soft trail)\r\n\r\nMood: Calm, romantic, graceful\r\n\r\nBest For: Daily wear, gifting, soft-spoken personalities\r\n\r\nDesign Style: Natural elegance with earthy tones and floral accents\r\n\r\nIdeal Season: Spring and early winter evenings\r\n\r\nGender Profile: Feminine leaning, but beautifully unisex for those who love floral warmth', 'Sweet', '2025-10-05', 1),
(34, '3', 'Kaliy instance', 250, '2025-10-05_product34.png', 'Kaliy is a bold, mysterious fragrance that evokes power, passion, and elegance. Designed for those who leave a lasting impression.', '50ml', 'Kaliy by Sugandhak Perfume is a tribute to intensity and allure. With its deep red bottle and copper crown, it speaks of royalty and fire. The scent is crafted for those who embrace their strength and sensuality—perfect for evening wear, grand entrances, and unforgettable moments.\r\n\r\nThe visual elements—red rose, amber resin, and earthy textures—reflect the perfume’s emotional depth and luxurious character. Kaliy is not just a fragrance; it’s a mood, a presence, a signature.', 'Fragrance Family: Oriental / Spicy / Woody (based on visual cues—can be adjusted once notes are finalized)\r\n\r\nLongevity: 8–10 hours\r\n\r\nSillage: Strong and captivating\r\n\r\nBest For: Nightlife, festive occasions, bold personalities\r\n\r\nDesign Style: Regal, intense, dramatic\r\n\r\nIdeal Season: Winter, festive nights\r\n\r\nGender Profile: Unisex leaning toward masculine elegance', 'Stronge', '2025-10-05', 1),
(35, '1', 'Magic Intense', 399, '2025-10-05_product35.png', 'Magic Intense is a radiant blend of citrus and creamy vanilla, wrapped in soft musk. A fragrance that glows with charm and sophistication.', '50ml', 'Magic Intense by Sugandhak Perfume is crafted for those who shine from within. It opens with a burst of fresh orange, awakening the senses with vibrant energy. The heart reveals soft vanilla flower—gentle, romantic, and comforting. As it settles, the base of rich vanilla and smooth musk creates a warm, lingering trail that feels both luxurious and inviting.\r\n\r\nThe golden bottle and sparkling background reflect the perfume’s magical aura—perfect for festive nights, elegant gatherings, or moments when you want to feel truly special.', 'Fragrance Family: Gourmand Floral\r\n\r\nLongevity: 7–9 hours\r\n\r\nSillage: Moderate to strong\r\n\r\nBest For: Celebrations, gifting, evening wear\r\n\r\nDesign Style: Golden elegance with warm, aromatic notes\r\n\r\nIdeal Season: Autumn, winter, festive occasions\r\n\r\nGender Profile: Feminine leaning, but beautifully unisex for lovers of vanilla warmth', 'Stronge', '2025-10-05', 1);
INSERT INTO `products` (`p_id`, `p_cat`, `p_nm`, `p_price`, `p_img`, `p_short_desc`, `p_weight`, `p_description`, `p_add_info`, `p_flavor`, `p_time`, `p_status`) VALUES
(36, '2', 'Envy Intense', 259, '2025-10-05_product36.png', 'Envy Intense is a seductive blend of exotic orchid, warm cinnamon, and creamy vanilla. A fragrance that turns heads and stirs desire.', '50ml', 'Envy Intense by Sugandhak Perfume is crafted for those who embrace mystery and magnetism. The top note of orchid sets a floral yet exotic tone, followed by the spicy warmth of cinnamon at the heart. The base of smooth vanilla adds depth and sensuality, creating a long-lasting trail that’s both elegant and provocative.\r\n\r\nThe deep purple bottle and matching cap reflect the perfume’s bold character—luxurious, confident, and unforgettable. Surrounded by rich textures and floral accents, Envy Intense is designed for nights when you want to be noticed without saying a word.', 'Fragrance Family: Floral Spicy Gourmand\r\n\r\nLongevity: 8–10 hours\r\n\r\nSillage: Strong and lingering\r\n\r\nBest For: Nightlife, romantic evenings, bold personalities\r\n\r\nDesign Style: Dark elegance with rich purple tones\r\n\r\nIdeal Season: Winter, festive nights\r\n\r\nGender Profile: Feminine leaning, but perfect for anyone who loves intense floral warmth', 'Stronge', '2025-10-05', 1),
(37, '3', 'Jealous Intense', 399, '2025-10-05_product37.png', 'Jealous Intense is a vibrant blend of citrus, spice, and creamy vanilla. A fragrance that commands attention with bold warmth and golden charm.', '50ml', 'Jealous Intense by Sugandhak Perfume is crafted for those who radiate confidence and charisma. It opens with the zesty brightness of lemon and the sweet depth of fig, creating an energetic and juicy start. The heart reveals a spicy mix of cinnamon and cardamom—fiery, aromatic, and unforgettable. As it settles, smooth vanilla wraps the scent in warmth, leaving a luxurious trail that lingers.\r\n\r\nThe golden bottle and rich ingredients reflect a fragrance made for festive nights, bold personalities, and moments that deserve to be remembered.', 'Fragrance Family: Citrus Spicy Gourmand\r\n\r\nLongevity: 8–10 hours\r\n\r\nSillage: Strong and expressive\r\n\r\nBest For: Celebrations, weddings, evening wear\r\n\r\nDesign Style: Golden elegance with natural spice\r\n\r\nIdeal Season: Autumn, winter, festive occasions\r\n\r\nGender Profile: Unisex with a bold, slightly masculine edge', 'Stronge', '2025-10-05', 1),
(38, '2', 'Charm Intense', 399, '2025-10-05_product38.png', 'Charm Intense is a graceful blend of white florals, soft peach, and smooth musk. A fragrance that whispers elegance and leaves a gentle trail.', '50ml', 'Charm Intense by Sugandhak Perfume is designed for those who carry quiet confidence and timeless grace. It opens with delicate white flowers—fresh, pure, and romantic. The heart reveals soft peach blossom, adding a subtle sweetness and warmth. The base of smooth musk creates a clean, lingering finish that feels intimate and refined.\r\n\r\nThe bottle’s round shape and golden cap reflect understated luxury, while the peach-toned liquid and floral accents evoke softness and serenity. Charm Intense is perfect for daily wear, intimate gatherings, or moments when elegance speaks louder than words.', 'Fragrance Family: Floral Musk\r\n\r\nLongevity: 6–8 hours\r\n\r\nSillage: Soft to moderate\r\n\r\nBest For: Daytime wear, gifting, graceful personalities\r\n\r\nDesign Style: Minimalist elegance with floral freshness\r\n\r\nIdeal Season: Spring, early winter mornings\r\n\r\nGender Profile: Feminine leaning, but beautifully wearable for anyone who loves soft florals', 'Sweet', '2025-10-05', 1),
(39, '5', 'Starlight Serenity', 149, '2025-10-06_attar1.png', 'SUGANDHAK Starlight Serenity is a 10 mL Eau de Parfum with dreamy, pastel-glitter packaging.', '10ml', 'Starlight Serenity is a perfume by SUGANDHAK. It is presented in an elegant glass bottle with a silver-toned cap, accompanied by a beautifully designed box featuring a watercolor-like blend of pastel purples, blues, and oranges, accented with silver glitter speckles. The label on both the box and the bottle clearly indicates the product name and brand, specifying that it is an Eau de Parfum in a 10 mL size.', 'Brand: SUGANDHAK PERFUME\r\n\r\nProduct Name: Starlight Serenity\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume/Size: 10 mL\r\n\r\nPackaging: Glass bottle with a metal-look cap and a multi-colored, glitter-accented box.', 'Sweet', '2025-10-06', 1),
(40, '5', 'Desert Whisper', 149, '2025-10-06_attar2.png', 'SUGANDHAK Desert Whisper is a 10 mL Eau de Parfum with a warm, amber liquid, packaged in a dramatic box featuring earthy tones and shimmering gold glitter.', '10ml', 'Desert Whisper is an evocative Eau de Parfum presented by SUGANDHAK PERFUME. This fragrance is housed in a clear, modern 10 mL glass bottle, allowing the warm, amber-toned liquid to shine through. The packaging is a striking visual representation of its name, featuring an artistic blend of earthy, burnt-orange, and deep-red watercolor splashes reminiscent of desert sands and sunsets. The box is luxuriously detailed with rich, sparkling gold glitter accents that evoke shimmering heat and golden dunes. With a sophisticated rose-gold cap, the perfume suggests a warm, mysterious, and intoxicating scent profile, perfect for those seeking a bold and grounding aroma that captures the essence of a desert landscape.', 'Brand: SUGANDHAK PERFUME\r\n\r\nProduct Name: Desert Whisper\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume/Size: 10 mL\r\n\r\nLiquid Color: Warm Amber/Orange\r\n\r\nPackaging Theme: Desert sunset with gold glitter accents and a watercolor effect.\r\n\r\nCap Color: Rose Gold/Copper tone.', 'Spicy', '2025-10-06', 1),
(41, '5', 'Midnight Ocean ', 149, '2025-10-06_attar3.png', 'SUGANDHAK Midnight Ocean is a 10 mL blue Eau de Parfum packaged in a striking box featuring deep blue watercolor effects and shimmering silver glitter, evoking a mysterious aquatic theme.', '10ml', 'Midnight Ocean is an immersive Eau de Parfum from SUGANDHAK PERFUME, capturing the cool, deep essence of the sea at night. The fragrance itself is a striking blue-green color, visible through the clear, compact 10 mL glass bottle, topped with a sleek, silver-toned cap. The outer packaging is designed to evoke the dramatic, mysterious depths of the ocean, featuring a watercolor wash of rich navy, deep teal, and lighter aqua blues. This aquatic pattern is dramatically accented with shimmering silver glitter that suggests sea spray or starlight reflecting on the waves. The name \"Midnight Ocean\" is elegantly scripted in metallic gold, hinting at a fresh, complex, and invigorating marine scent profile.', 'Brand: SUGANDHAK PERFUME\r\n\r\nProduct Name: Midnight Ocean\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume/Size: 10 mL\r\n\r\nLiquid Color: Blue/Teal\r\n\r\nPackaging Theme: Deep ocean/water with silver glitter and a watercolor effect.\r\n\r\nCap Color: Silver/Chrome.', 'Stronge', '2025-10-06', 1),
(42, '1', 'Cherry Blossom', 149, '2025-10-06_attar4.png', 'SUGANDHAK Cherry Blossom Dreams is a 10 mL pink Eau de Parfum packaged in a delicate box with pastel pink and blue watercolors and bright gold glitter, suggesting a light floral scent.', '10ml', 'Cherry Blossom Dreams is a delicate and airy Eau de Parfum from SUGANDHAK PERFUME. The fragrance is contained within a clear, 10 mL glass bottle, showcasing a pale, blush-pink liquid that reflects its floral theme. The bottle is topped with a modern, silver-toned cap. The outer packaging embodies a soft, springtime aesthetic, featuring a charming watercolor design in gentle hues of baby pink, light blue, and creamy white. This dreamy backdrop is beautifully contrasted with vibrant, sparkling gold glitter accents, suggesting a sunny and joyful mood. The product name, though slightly different on the box (\"Cherry Blossoms\") and bottle (\"Cherry Blossom Dreams\"), clearly indicates a light, sweet, and romantic floral scent, perfect for everyday wear.', 'Brand: SUGANDHAK PERFUME\r\n\r\nProduct Name (Bottle): Cherry Blossom Dreams\r\n\r\nProduct Name (Box): Cherry Blossoms\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume/Size: 10 mL\r\n\r\nLiquid Color: Pale Pink/Blush\r\n\r\nPackaging Theme: Springtime floral with pink and blue watercolors and gold glitter accents.\r\n\r\nCap Color: Silver/Chrome.', 'Sweet', '2025-10-06', 1),
(43, '5', 'Crimson Empire', 149, '2025-10-06_attar5.png', 'SUGANDHAK Crimson Empire is a 10 mL Eau de Parfum with a deep amber liquid, packaged in a bold box featuring dramatic crimson watercolors and rich gold glitter, suggesting an intense scent.', '10ml', 'Crimson Empire is a commanding and luxurious Eau de Parfum by SUGANDHAK PERFUME. This rich fragrance is presented in a clear, 10 mL glass bottle, allowing the deep, reddish-brown, amber-toned liquid to be seen, suggesting an intense and warm aroma. The bottle is finished with a sophisticated, brushed silver cap. The outer packaging makes a bold statement, featuring a dramatic watercolor design in various shades of deep crimson and maroon, evoking a sense of power and opulence. This rich background is stunningly enhanced by lavish, shimmering gold glitter accents. The name \"Crimson Empire\" is scripted in gold, positioning this fragrance as a captivating, authoritative, and deeply alluring scent perfect for evening wear or special occasions.', 'Brand: SUGANDHAK PERFUME\r\n\r\nProduct Name: Crimson Empire\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume/Size: 10 mL\r\n\r\nLiquid Color: Deep Amber/Reddish-Brown\r\n\r\nPackaging Theme: Rich, powerful crimson/maroon watercolors with heavy gold glitter accents, suggesting royalty and luxury.\r\n\r\nCap Color: Silver/Brushed Metal.', 'Alcohol', '2025-10-06', 1),
(44, '5', 'Forest Whispers', 149, '2025-10-06_attar6.png', 'SUGANDHAK Forest Whispers is a 10 mL golden-amber Eau de Parfum packaged in a deep green, earthy box with rich gold glitter, suggesting a warm and natural scent.', '10ml', 'Forest Whispers is an earthy and enchanting Eau de Parfum from SUGANDHAK PERFUME. The fragrance is contained in a clear, 10 mL glass bottle, which displays the warm, golden-amber liquid, hinting at a natural and grounding scent profile. The bottle is elegantly finished with a rich, rose-gold or copper-toned cap. The outer packaging visually captures the mystique of a forest, featuring a moody watercolor blend of deep greens, mossy hues, and earthy browns. This woodland backdrop is dramatically illuminated by heavy, sparkling gold glitter accents, suggesting sunlight filtering through a canopy. The name \"Forest Whispers\" is scripted in gold, positioning this fragrance as a warm, aromatic, and comforting scent that brings the tranquility of nature indoors.', 'Brand: SUGANDHAK PERFUME\r\n\r\nProduct Name: Forest Whispers\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume/Size: 10 mL\r\n\r\nLiquid Color: Golden Amber\r\n\r\nPackaging Theme: Forest/Nature with green and brown watercolors and heavy gold glitter accents.\r\n\r\nCap Color: Rose Gold/Copper tone.', 'Herbal', '2025-10-06', 1),
(45, '5', 'Oceanic Dusk', 149, '2025-10-06_attar7.png', 'SUGANDHAK Oceanic Dusk is a 10 mL coral-pink Eau de Parfum in a vibrant box with sunset-colored watercolors and gold glitter, suggesting a dramatic blend of warm and aquatic notes.', '10ml', 'Oceanic Dusk is a captivating Eau de Parfum by SUGANDHAK PERFUME, designed to evoke the dramatic colors of a sunset over the sea. The fragrance is presented in a clear, 10 mL glass bottle, which holds a distinctive coral-pink or reddish liquid. It is topped with a premium, bright gold-toned cap. The outer packaging is particularly striking, featuring an artistic watercolor blend of fiery coral, warm pinks, and deep ocean blues, symbolizing the twilight transition. This vibrant blend is contrasted and enhanced by rich, sparkling gold glitter accents, suggesting reflections of the setting sun on the water. The name \"Oceanic Dusk\" hints at a complex scent that balances warm, fruity or spicy notes with fresh, aquatic elements, making it ideal for a vibrant and romantic evening.', 'Brand: SUGANDHAK PERFUME\r\n\r\nProduct Name: Oceanic Dusk\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume/Size: 10 mL\r\n\r\nLiquid Color: Coral Pink/Reddish\r\n\r\nPackaging Theme: Sunset over the ocean, featuring coral and blue watercolors with heavy gold glitter accents.\r\n\r\nCap Color: Bright Gold/Brass tone.', 'Smoky', '2025-10-06', 1),
(46, '5', 'Royal Bloom', 149, '2025-10-06_attar8.png', 'SUGANDHAK Royal Bloom is a 10 mL deep purple Eau de Parfum, presented in a luxurious box with rich purple tones and dramatic gold glitter, suggesting a powerful, opulent floral scent.', '10ml', 'Royal Bloom is a luxurious and intense Eau de Parfum from SUGANDHAK PERFUME. The fragrance liquid is a deep, jewel-toned violet or royal purple, prominently displayed within the clear, substantial 10 mL glass bottle. The bottle is finished with a sleek, brushed silver-toned cap. The outer packaging is designed to communicate opulence and depth, featuring rich shades of purple and maroon, reminiscent of royal velvet. This dark, majestic backdrop is dramatically accented by massive, shimmering gold glitter bursts, which evoke a sense of grandeur and extravagance. The name \"Royal Bloom,\" scripted in gold, suggests a rich, potent, and possibly intense floral or oriental scent, perfect for making a memorable and powerful statement.', 'Brand: SUGANDHAK PERFUME\r\n\r\nProduct Name: Royal Bloom\r\n\r\nProduct Type: Eau de Parfum (EDP)\r\n\r\nVolume/Size: 10 mL\r\n\r\nLiquid Color: Deep Violet/Royal Purple\r\n\r\nPackaging Theme: Royal opulence, featuring deep purple hues and heavy gold glitter accents.\r\n\r\nCap Color: Silver/Brushed Metal.', 'Stronge', '2025-10-06', 1),
(47, '5', 'Eternal Spice', 149, '2025-10-06_attar9.png', 'SUGANDHAK Eternal Spice is a 10 mL deep amber Eau de Parfum, packaged in a dramatic box with forest green and smoky gold colors, suggesting a potent and warm oriental spice scent.', '10ml', 'Eternal Spice (SUGANDHAK PERFUME) is a warm and mysterious Eau de Parfum presented in a compact 10 mL clear glass bottle. The fragrance liquid is a rich, deep amber-brown, visible beneath a striking matte black cap and a dark green label. The outer box design is highly atmospheric, featuring a dramatic watercolor blend of deep forest green and warm, smoky orange/gold, accented with subtle gold glitter. This packaging suggests a potent, long-lasting, and complex scent profile, dominated by warm, oriental, or woody spice notes, making it an ideal choice for sophisticated wear.', 'Product: Eternal Spice Eau de Parfum\r\n\r\nBrand: SUGANDHAK PERFUME\r\n\r\nType: Warm and Mysterious Spice Scent\r\n\r\nBottle:\r\n\r\nSize: 10 mL glass bottle.\r\n\r\nLiquid Color: Rich, deep amber or brown.\r\n\r\nCap: Matte black.\r\n\r\nLabel: Dark green.', 'Alcohol', '2025-10-06', 1),
(48, '5', ' aqua attar', 149, '2025-10-06_attar10.png', 'A vibrant and luxurious SUGANDHAK perfume called \"aqua attar\" in a 100 mL Eau De Parfum concentration, featuring a striking magenta bottle and dramatic dark blue and gold packaging.', '10ml', 'Brand Name: SUGANDHAK PERFUME\r\n\r\nProduct Name: aqua attar (on the box) / aqua (on the bottle)\r\n\r\nProduct Type: Eau De Parfum\r\n\r\nVolume: 100 mL\r\n\r\nPackaging Appearance:\r\n\r\nBottle: Sleek, modern glass bottle with a vibrant magenta/deep pink color that fades to purple at the bottom. It has a black cap.\r\n\r\nBox: Dark blue/navy background with striking magenta/pink cloud-like plumes and scattered gold glitter/speckles. The text is white or gold.', 'Aesthetic: The packaging suggests a luxurious, rich, and possibly mystical or evening scent profile, indicated by the dark colors, vibrant magenta, and gold glitter.\r\n\r\nName Hint: The word \"aqua\" suggests a fresh, watery, or clean aspect to the fragrance, contrasting slightly with the deep, dramatic colors. The word \"attar\" implies a traditional, concentrated oil-based fragrance origin, though the product is labeled as an Eau De Parfum.', 'Herbal', '2025-10-06', 1),
(49, '6', 'Oud', 399, '2025-10-09_bodyspray1.png', 'A powerful, long-lasting, and classy body spray for men. Features a rich, mysterious scent of Oud, Whisky, and Patchouli.', '150ml', 'The Scent Experience: \'OUD\' - A Blend of Sophistication and Mystery\r\n\r\nElevate your personality with a depth and distinctiveness that comes with the \'OUD\' Body Spray. This fragrance delivers a powerful, yet refined experience.\r\n\r\nTop Note: The rich and warm Whisky top note provides an immediate attraction and profoundness, setting your presence apart.\r\n\r\nMiddle Note: The heart of the fragrance, Coriander, introduces an earthy, herbal, and subtly spicy character that perfectly balances the warm opening.\r\n\r\nBase Note: The Patchouli base note ensures long-lasting wear and a mysterious aura. It\'s a blend of sweet, earthy, and woody facets that anchors the fragrance with incredible longevity.\r\n\r\n\'OUD\' is the ideal choice for the modern man who appreciates classic grandeur and captivating mystery.', 'Brand: SUGANDHAK PERFUME\r\n\r\nScent Name: OUD\r\n\r\nIdeal For: Men\r\n\r\nScent Profile: Woody & Spicy\r\n\r\nBottle Color: Dark Brown/Black ', 'Woody', '2025-10-09', 1),
(50, '6', 'Night', 399, '2025-10-09_bodyspray2.png', 'A captivating and modern body spray for an evening out. It features a sophisticated blend of citrus, floral, and warm amber for a long-lasting, alluring scent.', '150ml', 'The SUGANDHAK NIGHT Body Spray is your perfect accessory for the evening. It opens with the dazzling and energetic scent of Grapefruit, which instantly grabs attention. This bright start smoothly transitions into a core of White Flower, lending a clean, refined, and effortlessly charming quality to the fragrance. The scent finally settles into a powerful base of warm Amber, giving it a rich, oriental depth that is both comforting and highly attractive. Designed to be long-lasting, \'NIGHT\' creates an alluring and memorable aura perfect for dinner, parties, or any late-hour occasion.', 'Brand: SUGANDHAK PERFUME\r\n\r\nScent Name: NIGHT\r\n\r\nScent Profile: Oriental, Fresh, and Floral\r\n\r\nIdeal For: Men and Women (Unisex appeal due to the fresh and warm notes)\r\n\r\nUse: Evening Wear / Special Occasions', 'Smoky', '2025-10-09', 1),
(51, '6', 'Blanc', 349, '2025-10-09_bodyspray3.png', 'A clean, fresh, and light body spray for daily use. Features a serene blend of Lavender, Neroli, and Musk for an effortlessly elegant scent.', '150ml', 'The SUGANDHAK BLANC Body Spray is the essence of pure freshness. It opens with the soothing clarity of Lavender, immediately setting a calm and refreshing tone. This is beautifully complemented by the bright, slightly honeyed Neroli in the middle, adding an elegant, sunny touch. The scent is grounded by a classic, clean Musk base, leaving a soft, powdery trail that is perfect for professional settings or casual day wear. \'BLANC\' is designed for those who prefer a light, crisp, and beautifully simple fragrance.', 'Brand: SUGANDHAK PERFUME\r\n\r\nScent Name: BLANC (Meaning: White/Clean)\r\n\r\nIdeal For: Men and Women (Truly Unisex)\r\n\r\nScent Profile: Clean, Floral, and Musky\r\n\r\nUse: Daily Wear / Office\r\n\r\nBottle Color: Crisp White (As pictured)', 'Sweet', '2025-10-09', 1),
(52, '6', 'Aqua', 349, '2025-10-09_bodyspray4.png', 'A fresh, energizing, and aquatic body spray for an instantly refreshing feel. It features a cool blend of Bergamot, Marine, and Amber perfect for everyday vitality.', '150ml', 'The SUGANDHAK AQUA Body Spray is like a refreshing splash of ocean air. It kicks off with the sharp, sunny burst of Bergamot, instantly awakening your senses. This is quickly followed by the cool, invigorating Marine heart, giving you that \'just out of the shower\' clean feeling. The scent smoothly finishes with a touch of warm Amber, providing a lasting, comforting foundation. \'AQUA\' is the ideal scent for active days, hot weather, or anyone who loves a light, crisp, and clean fragrance that keeps you feeling fresh all day.', 'Brand: SUGANDHAK PERFUME\r\n\r\nScent Name: AQUA\r\n\r\nIdeal For: Men\r\n\r\nScent Profile: Fresh, Aquatic, and Citrusy\r\n\r\nUse: Daily Wear / Gym / Summer\r\n\r\nBottle Color: Deep Charcoal Gray/Black with a Blue Label \r\n', 'Spicy', '2025-10-09', 1),
(53, '6', 'ORIENTAL SPICE', 399, '2025-10-09_bodyspray5.png', 'A bold, spicy, and warm body spray. It features a rich, exotic blend of Black Pepper, Leather, and Amberwood for a deeply masculine and unforgettable scent.', '150ml', 'The SUGANDHAK ORIENTAL SPICE Body Spray is a captivating journey for the senses. It commands attention from the start with a vibrant hit of Black Pepper. This intense opening gives way to a sophisticated, rugged heart of Leather and Coriander, creating a distinguished and masculine aroma. The fragrance settles into the luxurious warmth of Amberwood, ensuring the scent is both rich and enduring. This spray is perfect for men who seek an exotic, long-lasting, and intense fragrance for special occasions or when making a powerful statement.', 'Brand: SUGANDHAK PERFUME\r\n\r\nScent Name: ORIENTAL SPICE\r\n\r\nIdeal For: Men\r\n\r\nScent Profile: herbal and Leathery\r\n\r\nUse: Evening Wear / Special Occasions\r\n\r\nBottle Color: Classic Black ', 'Herbal', '2025-10-09', 1),
(54, '6', 'OCEAN BREEZE', 399, '2025-10-09_bodyspray6.png', 'An invigorating, marine, and fresh body spray. It captures the spirit of the open sea with notes of Sea Salt, Blue Cypress, and Ambergris for dynamic freshness.', '150ml', 'The SUGANDHAK OCEAN BREEZE Body Spray is an instant escape to the coast. It launches with a vibrant, salty splash from the Sea Salt and Grapefruit, giving you an immediate feeling of energy and cleanliness. The heart dives into the cool depth of the ocean with Aquatic Accord and a refreshing touch of Blue Cypress. Finally, the scent settles into a refined, long-lasting trail of Cedarwood and Ambergris, adding a sensual warmth that balances the extreme freshness. This spray is perfect for men who love powerful, fresh, and modern aquatic scents, making it ideal for daily wear or warmer weather.', 'Brand: SUGANDHAK PERFUME\r\n\r\nScent Name: OCEAN BREEZE\r\n\r\nIdeal For: Men\r\n\r\nScent Profile: Aquatic, Fresh, and Aromatic\r\n\r\nUse: Daily Wear / Warm Weather\r\n\r\nBottle Color: Deep Ocean Blue ', 'Alcohol', '2025-10-09', 1),
(55, '7', 'Lavender Mist', 299, '2025-11-06_room_spray1.png', 'Unwind with a single spray. Transform your home into a peaceful sanctuary with the soothing, natural aroma of fresh-cut Lavender. This Lavender Mist instantly banishes odors and infuses your space with a long-lasting, calming fragrance, perfect for relaxation, better sleep, and creating a welcoming ambiance.', '250ml', 'Step into a field of blooming lavender without leaving your couch. The Sugandhak Perfume Lavender Mist is an exquisitely formulated air freshener designed to elevate your mood and environment.\r\n\r\nCalming Aroma: Features the classic, therapeutic scent of lavender, well-known for its stress-reducing and sleep-enhancing qualities.\r\n\r\nInstant Freshness: Rapidly neutralizes stale and unwanted odors, leaving behind a clean, crisp, and delightful floral fragrance that lasts.\r\n\r\nVersatile Use: Ideal for bedrooms, bathrooms, living rooms, offices, and even linens. Use it as a room spray, linen spray, or pillow mist to set a tranquil mood.', 'Long-Lasting Formula: Designed to provide a fresh scent that lingers for hours.\r\n\r\nEasy-to-Use: Simple spray mechanism for a fine, wide mist application.\r\n\r\nFragrance Profile: A classic, natural lavender scent with subtle, fresh floral undertones.', 'Spicy', '2025-11-06', 1),
(56, '7', 'Ocean Fresh', 249, '2025-11-06_room_spray2.png', 'Experience the rush of the sea. Instantly invigorate your space with a crisp, clean burst of fresh ocean air. This Ocean Fresh scent is a revitalizing escape, leaving your home smelling like a beautiful coastal morning.', '250ml', 'Bring the refreshing, airy scent of the seaside right into your living room. The Sugandhak Perfume Ocean Fresh mist captures the essence of crashing waves and cool sea breeze, perfectly blending clean and aquatic notes.\r\n\r\nInvigorating Scent: Features a lively, clean, and cool aquatic fragrance that is instantly uplifting and refreshing.\r\n\r\nPowerful Odor Control: Rapidly eliminates tough odors in kitchens, bathrooms, and living areas, replacing them with a bright, lasting freshness.\r\n\r\nPerfect for Any Room: Ideal for spaces that need a quick, powerful refresh and a clean, neutral yet captivating aroma.', 'Fragrance Profile: Clean, Aquatic, and Airy with subtle marine notes.\r\n\r\nMood: Energizing, Crisp, and Refreshing.\r\n\r\nUsage: Can be used as a room spray, car freshener, or to quickly refresh towels and linens.', 'Stronge', '2025-11-06', 1),
(57, '7', 'Sandalwood & Rose', 299, '2025-11-06_room_spray3.png', 'An Ancient, Luxurious Embrace. Infuse your space with the rich, warm depth of Sandalwood softened by the romantic, delicate bloom of Rose. This is a classic, captivating fragrance that creates a truly luxurious and timeless ambiance.', '250ml', 'Elevate your home with this exquisite blend that speaks of heritage and tranquility. The Sandalwood & Rose mist perfectly marries two of the most revered scents in perfumery.\r\n\r\nWarm & Woody Base: The rich, creamy essence of Sandalwood provides a grounding and lasting foundation.\r\n\r\nVelvety Floral Heart: The timeless fragrance of fresh Rose petals adds a sweet, romantic lift to the blend.\r\n\r\nMood: Elegant, calming, luxurious, and deeply comforting. Ideal for living rooms, bedrooms, or entrance ways where you want to make a sophisticated impression.', 'Fragrance Profile: Traditional, Floral-Woody, and Sweet.\r\n\r\nLong-Lasting: The depth of sandalwood ensures the aroma lingers and provides continuous freshness.\r\n\r\nUsage: A powerful spray to quickly neutralize odors while imbuing your room with a serene, exotic scent.', 'Sweet', '2025-11-06', 1),
(58, '7', 'Green Tea & Mint', 349, '2025-11-06_room_spray4.png', 'Instant Spa Refreshment. Awaken your senses with the clean, crisp clarity of Green Tea perfectly blended with the cooling, bright burst of Mint. This invigorating mist is your daily dose of wellness and freshness, leaving your space feeling light, clean, and energized.', '250ml', 'Inspired by a tranquil spa experience, the Sugandhak Perfume Green Tea & Mint mist creates an atmosphere of revitalization and focused calm. This unique fragrance is designed to soothe the mind while providing a powerful, clean aroma.\r\n\r\nAromatic Clarity: The subtle, earthy notes of Green Tea promote a feeling of well-being and purification.\r\n\r\nCooling Uplift: The sharp, refreshing scent of Mint provides an immediate energy boost, clearing the air and the mind.\r\n\r\nPerfect for Focus: Ideal for home offices, yoga spaces, kitchens, or any area where you want a clean, non-cloying, and stimulating fragrance.', 'Fragrance Profile: Herbal, Fresh, Citrusy (Mint), and Clean.\r\n\r\nTherapeutic Feel: Known to aid in relaxation, mental clarity, and relieving stuffiness.\r\n\r\nUsage: A refreshing spritz to neutralize cooking odors or create a calming environment before a meeting or meditation.', 'Alcohol', '2025-11-06', 1),
(59, '7', 'Wild Berry', 349, '2025-11-06_room_spray5.png', 'A Burst of Fruity Delight. Indulge your senses with the sweet, juicy, and vibrant aroma of freshly picked forest berries. This Wild Berry mist is a playful, cheerful, and captivating scent that instantly lifts the mood in any room.', '200ml', 'Bring the sweet, luscious scent of a berry patch indoors. The Sugandhak Perfume Wild Berry mist is a complex blend of rich, ripe raspberries, tangy blueberries, and deep blackberries, creating a fragrance that is both comforting and exciting.\r\n\r\nSweet & Cheerful: Features a dominant, natural fruity sweetness that is highly appealing and long-lasting.\r\n\r\nInviting Aroma: Instantly creates a warm, welcoming, and vibrant atmosphere in your home.\r\n\r\nOdor Masking: Excellent for quickly masking odors in common areas like the kitchen or living room with a delightful fruity fragrance.', 'Fragrance Profile: Fruity, Sweet, Juicy, and Vibrant.\r\n\r\nMood: Happy, Playful, and Welcoming.\r\n\r\nUsage: Perfect for creating a festive or casual ambiance.', 'Sweet', '2025-11-06', 1),
(60, '7', 'Vanilla & Coconut', 349, '2025-11-06_room_spray7.png', 'Your Tropical Getaway in a Can. Escape to a sunny beach with the creamy, warm sweetness of Vanilla blended with the exotic, refreshing scent of Coconut. This mist is pure indulgence, creating an ambiance of warmth, comfort, and tropical relaxation.', '200ml', 'This fragrance is a decadent treat for your home. The Vanilla & Coconut mist combines two beloved, comforting notes to deliver a rich, warm, and inviting atmosphere that smells like a perpetual vacation.\r\n\r\nDecadent Comfort: The classic, rich, and comforting scent of vanilla is the perfect counterpoint to the light, airy sweetness of coconut.\r\n\r\nTropical Warmth: Reminiscent of a sunny day on a tropical beach, it evokes feelings of warmth and relaxation.\r\n\r\nIdeal for Cozy Spaces: Perfect for infusing bedrooms, living rooms, and dressing areas with a sweet, luxurious aroma.', 'Fragrance Profile: Sweet, Tropical, Creamy, and Warm.\r\n\r\nMood: Relaxing, Indulgent, and Comforting.\r\n\r\nUsage: A powerful spray to instantly transform any space into a cozy, fragrant sanctuary.', 'Woody', '2025-11-06', 1),
(61, '7', 'Citrus & Verbena', 299, '2025-11-06_room_spray6.png', 'Sunlight in a Spray. Instantly brighten your mood and space with the zesty, clean burst of fresh Citrus and the delicate, lemony lift of Verbena. This vibrant mist is perfect for creating a cheerful, spotlessly clean, and energizing atmosphere.', '250ml', 'Invigorate your surroundings with this classic, uplifting blend. The Sugandhak Perfume Citrus & Verbena mist is a powerhouse of clean, joyful fragrance designed to eliminate lingering smells and replace them with pure, sunny freshness.\r\n\r\nZesty Cleanliness: Features sharp notes of lemon, lime, and orange, which are naturally deodorizing and highly stimulating.\r\n\r\nHerbal Sophistication: Verbena adds a subtle, refined herbal-citrus layer, making the scent crisp and sophisticated, not just sweet.\r\n\r\nMood: Highly energizing, mood-boosting, and clarifying. Perfect for spaces where you work or entertain.', 'Fragrance Profile: Bright, Zesty, Herbal-Citrus, and Clean.\r\n\r\nScent Intensity: Strong and immediate, perfect for quick refreshers.\r\n\r\nUsage: Ideal for kitchens, entryways, or anywhere a fresh, clean scent is desired.', 'Alcohol', '2025-11-06', 1);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

CREATE TABLE `users` (
  `u_id` int(10) NOT NULL,
  `u_fnm` varchar(255) DEFAULT NULL,
  `u_email` varchar(100) DEFAULT NULL,
  `u_mno` int(10) DEFAULT NULL,
  `u_pwd` varchar(6) DEFAULT NULL,
  `u_time` varchar(100) NOT NULL,
  `u_status` int(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`u_id`, `u_fnm`, `u_email`, `u_mno`, `u_pwd`, `u_time`, `u_status`) VALUES
(1, 'meet', 'meet@gmail.com', 2147483647, '123456', '2025-11-04', 1);

-- --------------------------------------------------------

--
-- Table structure for table `wishlist`
--

CREATE TABLE `wishlist` (
  `w_id` int(100) NOT NULL,
  `w_uid` int(100) DEFAULT NULL,
  `w_pid` int(100) DEFAULT NULL,
  `w_time` varchar(100) DEFAULT NULL,
  `w_status` int(1) NOT NULL DEFAULT 1
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`a_id`);

--
-- Indexes for table `category`
--
ALTER TABLE `category`
  ADD PRIMARY KEY (`cat_id`);

--
-- Indexes for table `contact`
--
ALTER TABLE `contact`
  ADD PRIMARY KEY (`co_id`);

--
-- Indexes for table `hero`
--
ALTER TABLE `hero`
  ADD PRIMARY KEY (`h_id`);

--
-- Indexes for table `latest_product`
--
ALTER TABLE `latest_product`
  ADD PRIMARY KEY (`l_id`);

--
-- Indexes for table `orders`
--
ALTER TABLE `orders`
  ADD PRIMARY KEY (`o_id`);

--
-- Indexes for table `products`
--
ALTER TABLE `products`
  ADD PRIMARY KEY (`p_id`);

--
-- Indexes for table `users`
--
ALTER TABLE `users`
  ADD PRIMARY KEY (`u_id`);

--
-- Indexes for table `wishlist`
--
ALTER TABLE `wishlist`
  ADD PRIMARY KEY (`w_id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `a_id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `category`
--
ALTER TABLE `category`
  MODIFY `cat_id` int(11) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=8;

--
-- AUTO_INCREMENT for table `contact`
--
ALTER TABLE `contact`
  MODIFY `co_id` int(10) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `hero`
--
ALTER TABLE `hero`
  MODIFY `h_id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=3;

--
-- AUTO_INCREMENT for table `latest_product`
--
ALTER TABLE `latest_product`
  MODIFY `l_id` int(50) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=6;

--
-- AUTO_INCREMENT for table `orders`
--
ALTER TABLE `orders`
  MODIFY `o_id` int(4) NOT NULL AUTO_INCREMENT;

--
-- AUTO_INCREMENT for table `products`
--
ALTER TABLE `products`
  MODIFY `p_id` int(4) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=62;

--
-- AUTO_INCREMENT for table `users`
--
ALTER TABLE `users`
  MODIFY `u_id` int(10) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;

--
-- AUTO_INCREMENT for table `wishlist`
--
ALTER TABLE `wishlist`
  MODIFY `w_id` int(100) NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=2;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
